FROM ba-forecasting-base:latest

WORKDIR /app

COPY api.py .
COPY data/ data/

EXPOSE 8000

CMD ["conda", "run", "--no-capture-output", "-n", "ba-forecasting", "uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
